springdoc:
  swagger-ui:
    path: /swagger-ui.html

custom:
  api:
    categories-url: https://kudago.com/public-api/v1.4/place-categories
    locations-url: https://kudago.com/public-api/v1.4/locations
    rate:
      limit: 2
    executor:
      pool-size: 4
  links:
    base-url: http://localhost:8080
  thread:
    pool:
      size: 1
  initialization:
    schedule: PT10S