name: CI Workflow

on:
  push:
    branches:
      - fj_2024_lesson_14
  pull_request:
    branches:
      - fj_2024_lesson_14

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', 'lab8/**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        working-directory: ./lab8
        run: ../gradlew build

      - name: Run tests and calculate coverage
        working-directory: ./lab8
        run: ../gradlew test jacocoTestReport

      - name: Run Checkstyle
        working-directory: ./lab8
        run: ../gradlew checkstyleMain checkstyleTest

      - name: Build Docker image
        run: docker build -t io.github.dziodzi/lab8:latest -f docker/Dockerfile .

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Packages
        run: |
          docker tag io.github.dziodzi/lab8:latest ghcr.io/${{ github.repository }}/lab8:latest
          docker push ghcr.io/${{ github.repository }}/lab8:latest
